# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: 'postgres:15.3'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rust-web-app
